Repository FRONT-END-BOOTCAMP-PLUS-5/KNACK, pull requests merged in 2025-08, with the labels that each got.

#10 [prisma] Payments 테이블 컬럼 추가
  prisma/schema.prisma
Labels: feat

#9 [feat] 장바구니 페이지 UI 작업 및 공통 컴포넌트 추가
  app/(user)/cart/cartPage.module.scss
  app/(user)/cart/page.tsx
  components/Cart/CartProduct/cartProduct.module.scss
  components/Cart/CartProduct/index.tsx
  components/Cart/PaymentButton/index.tsx
  components/Cart/PaymentButton/paymentButton.module.scss
  components/common/Button/button.module.scss
  components/common/Button/index.tsx
  components/common/Checkbox/checkbox.module.scss
  components/common/Checkbox/index.tsx
  components/common/ChipButton/chipButton.module.scss
  components/common/ChipButton/index.tsx
  components/common/Divider/divider.module.scss
  components/common/Divider/index.tsx
  components/common/Flex/flex.module.scss
  components/common/Flex/index.tsx
  components/common/Text/index.tsx
Labels: feat

#12 [prisma] products column add
  prisma/schema.prisma
Labels: prisma

#13 [feat] 어드민 상품등록 페이지, API 추가 및 prisma column 변경
  app/admin/layout.tsx
  app/admin/products/page.tsx
  app/admin/products/productsPage.module.scss
  app/api/admin/products/route.ts
  backend/admin/products/applications/dtos/ProductDto.ts
  backend/admin/products/applications/usecases/CreateProductUseCase.ts
  backend/admin/products/domains/entities/Product.ts
  backend/admin/products/domains/repositories/ProductRepository.ts
  backend/admin/products/repositories/PrProductsRepository.ts
  backend/utils/prisma.ts
  prisma/schema.prisma
Labels: feat

#7 [feat] login 퍼블리싱, credentials 로그인(nextauth, 로컬에서 임시구현)
  app/(user)/LayoutWrapper.tsx
  app/(user)/layout.tsx
  app/(user)/login/login.module.scss
  app/(user)/login/page.tsx
  app/api/auth/[...nextauth]/auth.ts
  app/api/auth/[...nextauth]/route.ts
  components/auth/SocialLogin/index.tsx
  components/auth/SocialLogin/socialLogin.module.scss
  components/common/AuthInput/authInput.module.scss
  components/common/AuthInput/index.tsx
  components/common/LoginForm/index.tsx
  components/common/LoginForm/loginForm.module.scss
  components/common/footer/Footer.tsx
  components/common/footer/footer.module.scss
  components/common/header/Header.tsx
  components/common/header/header.module.scss
  constraint/auth.ts
  constraint/header.ts
  hooks/useLoginValidation.ts
  package.json
  public/google_logo.svg
  public/kakaotalk_logo.svg
  types/auth.ts
  types/header.ts
  types/next-auth.d.ts
  utils/auth/validation.ts
  utils/header/index.ts
Labels: feat

#15 [refactor] 검색페이지 ui수정, svg 아이콘 별도 관리
  components/common/SearchModal/PopularKeywords.tsx
  components/common/SearchModal/RecentKeywords.tsx
  components/common/SearchModal/RecentProducts.tsx
  components/common/SearchModal/RecommendedTags.tsx
  components/common/SearchModal/SearchHeader.tsx
  components/common/SearchModal/index.tsx
  components/common/SearchModal/searchModal.module.scss
  public/icons/book_mark.svg
  public/icons/book_mark_active.svg
  public/icons/circle_close.svg
  public/icons/close.svg
  styles/_mixins.scss
Labels: refactor

#18 [feat] 상품페이지 UI 작업
  app/(user)/search/page.tsx
  components/common/BottomSheet/bottom_sheet.module.scss
  components/common/BottomSheet/index.tsx
  components/common/DragScroll/drag_scroll.module.scss
  components/common/DragScroll/index.tsx
  components/common/ProductCard/index.tsx
  components/common/ProductCard/product_card.module.scss
  components/search/SearchBottomSheet/index.tsx
  components/search/SearchBottomSheet/search_bottom_sheet.module.scss
  components/search/SearchFilter/index.tsx
  components/search/SearchFilter/search_filter.module.scss
  components/search/SearchProductList/index.tsx
  components/search/SearchProductList/search_product_list.module.scss
  components/search/SearchSort/index.tsx
  components/search/SearchSort/search_sort.module.scss
  constraint/product.ts
  package.json
  public/icons/arrow_down.svg
  public/icons/check_circle.svg
  public/icons/close_large.svg
  public/icons/filter_arrow.svg
  public/images/test_usagi.webp
  store/bottomSheetStore.ts
  styles/_colors.scss
Labels: feat

#19 [feat] 장바구니 옵션 변경 api 추가 및 연결, 다중삭제 api 추가 및 연결
  app/(user)/cart/cartPage.module.scss
  app/(user)/cart/page.tsx
  app/(user)/test/page.tsx
  app/admin/products/page.tsx
  app/api/cart/deletes/route.ts
  app/api/cart/route.ts
  backend/cart/applications/usecases/CreateCartUseCase.ts
  backend/cart/applications/usecases/DeleteCartUseCase.ts
  backend/cart/applications/usecases/DeletesCartUseCase.ts
  backend/cart/applications/usecases/GetCartUseCase.ts
  backend/cart/domains/entities/Cart.ts
  backend/cart/domains/repositires/CartRepository.ts
  backend/cart/repositories/PrCartRepository.ts
  backend/utils/prisma.ts
  components/Cart/CartProduct/index.tsx
  components/Cart/PaymentButton/index.tsx
  components/common/Button/button.module.scss
  components/common/Button/index.tsx
  components/common/Checkbox/index.tsx
  components/common/ConfirmModal/confirmModal.module.scss
  components/common/ConfirmModal/index.tsx
  components/common/Flex/index.tsx
  constraint/auth.ts
  constraint/cart.ts
  prisma/schema.prisma
  services/cart/index.ts
  types/brand.ts
  types/cart.ts
  types/category.ts
  types/product.ts
Labels: feat

#21 [hotfix] 폴더 이름 대소문자 변경, build error 수정
  app/(user)/cart/page.tsx
  components/cart/CartProduct/cartProduct.module.scss
  components/cart/CartProduct/index.tsx
  components/cart/PaymentButton/index.tsx
  components/cart/PaymentButton/paymentButton.module.scss
Labels: hotfix

#25 [prisma] order table paymentId nullable 추가
  prisma/schema.prisma
Labels: prisma

#26 [feat] 상품 상세 페이지 api 연결
  app/(user)/products/[id]/page.tsx
  app/(user)/products/[id]/productDetail.module.scss
  app/api/products/route.ts
  backend/products/applications/usecases/GetProductUseCase.ts
  backend/products/domains/entities/Product.ts
  backend/products/domains/repositories/ProductRepository.ts
  backend/products/repositories/PrProductsRepository.ts
  components/products/AdditionalBenefits/additionalBenefits.module.scss
  components/products/AdditionalBenefits/index.tsx
  components/products/BrandInfo/index.tsx
  components/products/DefaultInfo/index.tsx
  components/products/ProductDetailImage/index.tsx
  components/products/ProductTopImage/index.tsx
  components/products/ProductTopImage/productTopImage.module.scss
  components/products/TextReview/index.tsx
  components/products/TextReview/textReview.module.scss
  constraint/auth.ts
  services/products/index.ts
  types/productDetail.ts
Labels: feat

#27 [prisma] product, option_value, option_type table 수정
  app/admin/products/page.tsx
  app/admin/products/productsPage.module.scss
  backend/admin/products/applications/dtos/PostProductDto.ts
  backend/admin/products/applications/dtos/ProductDto.ts
  backend/admin/products/domains/entities/Product.ts
  backend/admin/products/repositories/PrProductsRepository.ts
  backend/products/domains/entities/Product.ts
  backend/products/repositories/PrProductsRepository.ts
  prisma/schema.prisma
Labels: prisma

#28 [prisma] payments table paymentNumber nullable
  backend/payments/repositories/KnackPaymentRepository.ts
  prisma/schema.prisma
Labels: prisma

#30 [prisma] paymentRepository 에 payment type null 추가
  backend/payments/applications/dtos/CreatePaymentDto.ts
Labels: prisma

#23 [feat] 상품 리스트 조회 백엔드 로직 추가
  app/(user)/search/page.tsx
  app/api/search/route.ts
  backend/search/applications/dtos/GetProductsDto.ts
  backend/search/applications/usecases/GetProductsUseCase.ts
  backend/search/domains/entities/Product.ts
  backend/search/domains/entities/ProductFilters.ts
  backend/search/domains/repositories/ProductSearchRepository.ts
  backend/search/infrastructure/repositories/PrProductsRepository.ts
  components/common/ProductCard/index.tsx
  components/common/ProductCard/product_card.module.scss
  components/search/SearchProductList/SearchProductListEmpty.tsx
  components/search/SearchProductList/index.tsx
  components/search/SearchProductList/search_product_list.module.scss
  hooks/useClearProductFilter.ts
Labels: feat

#29 회원탈퇴 기능 구현,Next.js 로그인 상태 미들웨어 기반 보안, Toast 컴포넌트 추가
  app/(user)/LayoutWrapper.tsx
  app/(user)/my/myPage.module.scss
  app/(user)/my/page.tsx
  app/(user)/my/withdrawal/page.tsx
  app/(user)/my/withdrawal/withdrawalPage.module.scss
  app/(user)/protected/layout.tsx
  app/api/auth/[...nextauth]/auth.ts
  app/api/withdrawal/route.ts
  backend/login/applications/dtos/LoginDto.ts
  backend/login/applications/usecases/LoginUseCase.ts
  backend/login/domains/entities/Login.ts
  backend/login/repositories/PrLoginRepository.ts
  backend/withdrawal/applications/dtos/WithdrawDto.ts
  backend/withdrawal/applications/usecases/WithdrawUseCase.ts
  backend/withdrawal/domains/entities/Withdraw.ts
  backend/withdrawal/domains/repositories/WithdrawRepository.ts
  backend/withdrawal/repositories/PrWithdrawRepository.ts
  components/common/Footer/footer.module.scss
  components/common/Footer/index.tsx
  components/common/Header/header.module.scss
  components/common/Header/index.tsx
  components/common/LoginForm/index.tsx
  components/common/LoginForm/loginForm.module.scss
  components/common/Toast/index.tsx
  components/common/Toast/toast.module.scss
  components/withdrawal/WithdrawalForm/index.tsx
  components/withdrawal/WithdrawalForm/withdrawalForm.module.scss
  components/withdrawal/WithdrawalInfo/index.tsx
  components/withdrawal/WithdrawalInfo/withdrawalInfo.module.scss
  hooks/useAuthGuard.ts
  hooks/useWithdraw.ts
  middleware.ts
  package.json
  prisma/schema.prisma
  services/auth/index.ts
  services/withdrawal/index.ts
  types/auth.ts
  types/withdrawal.ts
Labels: feat, refactor

#32 [feat] 상품 상세페이지, 장바구니 페이지 체크아웃 페이지와 연결
  app/(user)/LayoutWrapper.tsx
  app/(user)/cart/page.tsx
  app/(user)/products/[id]/page.tsx
  app/(user)/test/page.tsx
  app/admin/products/page.tsx
  backend/products/domains/entities/Product.ts
  backend/products/repositories/PrProductsRepository.ts
  components/cart/CartProduct/index.tsx
  components/cart/PaymentButton/index.tsx
  components/common/Text/index.tsx
  components/products/BottomFixButton/bottomFixButton.module.scss
  components/products/BottomFixButton/index.tsx
  components/products/DefaultInfo/index.tsx
  components/products/OptionBottomSheet/index.tsx
  components/products/OptionBottomSheet/optionBottomSheet.module.scss
  types/cart.ts
  types/productDetail.ts
Labels: feat

#36 전역상태 관리 , 소셜로그인(카카오톡), 헤더 푸터 분리, 로그아웃 추가
  app/(user)/LayoutWrapper.tsx
  app/(user)/my/myPage.module.scss
  app/(user)/userTest/page.tsx
  app/api/auth/[...nextauth]/auth.ts
  app/api/user/profile/route.ts
  backend/auth/applications/dtos/SocialLoginDto.ts
  backend/auth/applications/usecases/SocialLoginUseCase.ts
  backend/auth/domains/entities/SocialLogin.ts
  backend/auth/domains/repositories/SocialLoginRepository.ts
  backend/auth/repositories/PrSocialLoginRepository.ts
  components/auth/SocialLogin/index.tsx
  components/common/LogoutButton/index.tsx
  components/common/LogoutButton/logoutButton.module.scss
  store/userStore.ts
  types/next-auth.d.ts
Labels: feat, refactor, hotfix

#40 [feat] 상품 좋아요 추가, 삭제, 리스트 불러오는 API 추가
  app/(user)/saved/page.tsx
  app/(user)/saved/saved.module.scss
  app/api/likes/route.ts
  backend/likes/applications/dtos/LikeDto.ts
  backend/likes/applications/usecases/CreateLikesUseCase.ts
  backend/likes/applications/usecases/DeleteLikesUseCase.ts
  backend/likes/applications/usecases/GetLikesUseCase.ts
  backend/likes/domains/entities/Likes.ts
  backend/likes/domains/repositories/LikesRepository.ts
  backend/likes/repositories/PrLikesRepository.ts
  components/common/Footer/index.tsx
  components/my/address/AddressModal/addressModal.module.scss
  prisma/schema.prisma
  services/like/index.ts
  types/like.ts
Labels: feat

#41 [refactor] 상품 리스트 조회 api 일부 값 다중선택으로 백엔드 로직 수정 페이지 데이터 매핑, 조건부 스타일 추가
  app/(user)/search/page.tsx
  app/api/search/route.ts
  backend/search/applications/dtos/GetProductsDto.ts
  backend/search/domains/entities/ProductFilters.ts
  backend/search/infrastructure/repositories/PrProductsRepository.ts
  components/search/SearchCsrWrapper/index.tsx
  components/search/SearchFilter/index.tsx
  components/search/SearchFilter/searchFilter.module.scss
  components/search/SearchSort/index.tsx
  constraint/product.ts
  styles/_colors.scss
  types/searchProductList.ts
  utils/searchFilter.ts
  utils/searchParams.ts
Labels: feat, refactor

#44 [feat] save 상품 탭 부분 완성
  app/(user)/LayoutWrapper.tsx
  app/(user)/saved/page.tsx
  app/(user)/saved/saved.module.scss
  app/api/likes/route.ts
  app/api/products/[id]/route.ts
  app/api/products/route.ts
  backend/likes/applications/usecases/CreateLikesUseCase.ts
  backend/likes/applications/usecases/GetLikesUseCase.ts
  backend/likes/domains/repositories/LikesRepository.ts
  backend/likes/repositories/PrLikesRepository.ts
  backend/products/applications/usecases/GetIdsProductUseCase.ts
  backend/products/domains/entities/Products.ts
  backend/products/domains/repositories/ProductRepository.ts
  backend/products/repositories/PrProductsRepository.ts
  components/common/Flex/flex.module.scss
  components/common/Flex/index.tsx
  services/like/index.ts
  services/products/index.ts
  types/like.ts
  types/product.ts
Labels: feat

#46 [prisma] like 테이블 product_likes 로 변경, brand_likes 테이블 추가
  backend/likes/repositories/PrLikesRepository.ts
  backend/search/infrastructure/repositories/PrProductsRepository.ts
  prisma/schema.prisma
Labels: prisma

#47 [feat] 브랜드 좋아요 추가, 삭제, 조회 API, 테스트 연결 추가
  app/(user)/saved/page.tsx
  app/api/brand-likes/route.ts
  backend/brand-likes/applications/dtos/BrandLikeDto.ts
  backend/brand-likes/applications/usecases/CreateBrandLikesUseCase.ts
  backend/brand-likes/applications/usecases/DeleteBrandLikesUseCase.ts
  backend/brand-likes/applications/usecases/GetBrandLikesUseCase.ts
  backend/brand-likes/domains/entities/BrandLikes.ts
  backend/brand-likes/domains/repositories/BrandLikesRepository.ts
  backend/brand-likes/repositories/PrBrandLikesRepository.ts
  services/like/index.ts
  types/like.ts
Labels: feat

#45 [feat] 상품리스트 필터 바텀시트 카테고리 작업
  app/api/categories/route.ts
  app/api/search/route.ts
  backend/categories/applications/dtos/CategoryDto.ts
  backend/categories/applications/usecases/GetCategoryUsecase.ts
  backend/categories/domains/entities/Category.ts
  backend/categories/domains/repositories/CategoryRepository.ts
  backend/categories/repositories/PrCategoryRepository.ts
  backend/search/infrastructure/repositories/PrProductsRepository.ts
  components/search/SearchBottomSheet/SearchCategory.tsx
  components/search/SearchBottomSheet/index.tsx
  components/search/SearchBottomSheet/searchBottomSheet.module.scss
  components/search/SearchCsrWrapper/index.tsx
  components/search/SearchFilter/index.tsx
  constraint/product.ts
  services/category/index.ts
  types/category.ts
  utils/search/searchBottomSheetTab.ts
  utils/search/searchFilter.ts
Labels: feat, refactor

#49 [feat] Save 페이지 최근본 상품 API 추가 및 기능 연결
  app/(user)/saved/page.tsx
  app/api/likes/route.ts
  app/api/products/recent/route.ts
  backend/cart/applications/usecases/CreateCartUseCase.ts
  backend/cart/applications/usecases/DeleteCartUseCase.ts
  backend/cart/applications/usecases/DeletesCartUseCase.ts
  backend/cart/applications/usecases/GetCartUseCase.ts
  backend/cart/domains/repositories/CartRepository.ts
  backend/cart/repositories/PrCartRepository.ts
  backend/likes/applications/usecases/CreateLikesUseCase.ts
  backend/likes/domains/entities/Likes.ts
  backend/likes/domains/repositories/LikesRepository.ts
  backend/likes/repositories/PrLikesRepository.ts
  backend/products/applications/usecases/GetRecentlyProductUseCase.ts
  backend/products/domains/entities/RecentProduct.ts
  backend/products/domains/repositories/ProductRepository.ts
  backend/products/repositories/PrProductsRepository.ts
  components/saved/RecentlySave/index.tsx
  components/saved/RecentlySave/recently.module.scss
  prisma/schema.prisma
  services/like/index.ts
  services/products/index.ts
  types/product.ts
Labels: feat, prisma

#51 [feat] 상품목록 조회 바텀시트 브랜드 조회, 검색 추가
  app/api/brands/route.ts
  backend/brands/applications/dtos/BrandDto.ts
  backend/brands/applications/usecases/GetBrandUsecase.ts
  backend/brands/domains/entities/Brand.ts
  backend/brands/domains/repositories/BrandRepository.ts
  backend/brands/repositories/PrBrandRepository.ts
  components/common/BasicInput/index.tsx
  components/common/Text/index.tsx
  components/search/SearchBottomSheet/SearchBrand.tsx
  components/search/SearchBottomSheet/index.tsx
  hooks/useDebounce.ts
  services/brand/index.ts
  types/brand.ts
Labels: feat

#59 [feat] 고정 유저 아이디 제거, 상품상세, 최근본 상품, 브랜드 좋아요 카운트 수 추가
  app/(user)/saved/page.tsx
  app/api/cart/route.ts
  backend/brand-likes/domains/entities/BrandLikes.ts
  backend/brand-likes/repositories/PrBrandLikesRepository.ts
  backend/cart/applications/usecases/CreateCartUseCase.ts
  backend/cart/applications/usecases/GetCartUseCase.ts
  backend/cart/domains/repositories/CartRepository.ts
  backend/cart/repositories/PrCartRepository.ts
  backend/orders/applications/usecases/CreateOrderUseCase.ts
  backend/products/domains/entities/Product.ts
  backend/products/domains/entities/RecentProduct.ts
  backend/products/repositories/PrProductsRepository.ts
  components/products/BottomFixButton/bottomFixButton.module.scss
  components/products/BottomFixButton/index.tsx
  components/products/BrandInfo/brandInfo.module.scss
  components/products/BrandInfo/index.tsx
  components/products/DefaultInfo/index.tsx
  components/saved/BrandSave/index.tsx
  constraint/saved.ts
  types/cart.ts
  types/like.ts
  types/productDetail.ts
Labels: feat

#58 [refactor] 상품목록 로직 추가
  app/(user)/search/page.tsx
  backend/filter-counts/repositories/PrFilterCountsRepository.ts
  backend/search/infrastructure/repositories/PrProductsRepository.ts
  components/common/BottomSheet/bottom_sheet.module.scss
  components/search/SearchBottomSheet/index.tsx
  components/search/SearchBottomSheet/searchBottomSheet.module.scss
  components/search/SearchFilter/index.tsx
  components/search/SearchFilter/searchFilter.module.scss
  components/search/SearchProductList/index.tsx
  components/search/SearchSort/index.tsx
  components/search/SearchSort/searchSort.module.scss
  constraint/product.ts
  hooks/useClearProductFilter.ts
  public/icons/reset.svg
  services/search/index.ts
  styles/_colors.scss
  types/searchProductList.ts
  utils/queryString.ts
Labels: feat, refactor, hotfix

#60 [refactor] 상품 좋아요 리스트 불러오는 로직 수정
  app/(user)/saved/page.tsx
  backend/likes/domains/entities/Likes.ts
  backend/likes/repositories/PrLikesRepository.ts
  components/products/BottomFixButton/index.tsx
  components/saved/BrandSave/index.tsx
  components/saved/ProductSave/index.tsx
  components/saved/RecentlySave/index.tsx
  types/like.ts
Labels: refactor

#61 [hotfix] ids null check
  app/(user)/saved/page.tsx
Labels: hotfix

#63 [fix] 상품페이지 버그 개선
  app/(user)/search/page.tsx
  backend/search/infrastructure/repositories/PrProductsRepository.ts
  components/common/BottomSheet/index.tsx
  components/common/ProductCard/index.tsx
  components/search/SearchProductList/index.tsx
  components/search/SearchProductList/searchProductList.module.scss
Labels: hotfix

#69 [feat] 상품목록 무한스크롤 구현 완료
  app/(user)/search/page.tsx
  backend/search/infrastructure/repositories/PrProductsRepository.ts
  components/common/Flex/index.tsx
  components/common/ProductCard/index.tsx
  components/search/SearchProductList/index.tsx
  components/search/SearchProductList/searchProductList.module.scss
  hooks/useInfiniteScroll.ts
  public/images/loading.gif
  services/search/index.ts
Labels: bug, feat, refactor

#66 [feat] 리뷰페이지 구현 (상세페이지 상품리뷰 X)
  app/(user)/my/review/[orderId]/page.tsx
  app/(user)/my/review/[orderId]/reviewWrite.module.scss
  app/(user)/my/review/page.tsx
  app/(user)/my/review/review.module.scss
  app/api/reviews/orders/route.ts
  app/api/reviews/route.ts
  backend/reviews/applications/dtos/ReviewDto.ts
  backend/reviews/applications/usecases/CreateReviewUseCase.ts
  backend/reviews/applications/usecases/GetMyReviewsUseCase.ts
  backend/reviews/applications/usecases/GetReviewableOrdersUseCase.ts
  backend/reviews/domains/entities/Order.ts
  backend/reviews/domains/entities/Review.ts
  backend/reviews/repositories/PrOrderRepository.ts
  backend/reviews/repositories/PrReviewRepository.ts
  components/my/ActionGrid/actionGrid.module.scss
  components/my/ActionGrid/index.tsx
  hooks/useReview.ts
  hooks/useReviewCount.ts
  package.json
  services/review/index.ts
  store/userStore.ts
  types/react-stars.d.ts
  types/review.ts
  utils/review/index.ts
  utils/reviewUtils.ts
Labels: feat

#72 [feat] 상품 리스트, 카테고리 관련 로직 추가
  app/api/categories/route.ts
  backend/categories/applications/dtos/CategoryDto.ts
  backend/categories/domains/entities/Category.ts
  backend/categories/repositories/PrCategoryRepository.ts
  components/common/Header/HeaderCategory.tsx
  components/common/Header/header.module.scss
  components/common/Header/index.tsx
  components/common/ProductCard/productCard.module.scss
  components/search/SearchBottomSheet/SearchCategory.tsx
  components/search/SearchBottomSheet/index.tsx
  components/search/SearchCategory/index.tsx
  components/search/SearchCategory/searchCategory.module.scss
  components/search/SearchCsrWrapper/index.tsx
  components/search/SearchCsrWrapper/searchCsrWrapper.module.scss
  components/search/SearchFilter/searchFilter.module.scss
  components/search/SearchProductList/SearchProductListEmpty.tsx
  components/search/SearchSort/index.tsx
  constraint/auth.ts
  constraint/header.ts
  public/images/popular_adidas.webp
  public/images/popular_bag.webp
  public/images/popular_hat.webp
  public/images/popular_hoodie.webp
  public/images/popular_long_sleeve.webp
  public/images/popular_nike.webp
  public/images/popular_pants.webp
  public/images/popular_shoes.webp
  public/images/popular_tshirt.webp
  public/images/popular_windbreaker.webp
  services/category/index.ts
  store/categoryStore.ts
  types/category.ts
Labels: feat

#73 [hotfix] 상품 상세페이지 상품,브랜드 좋아요 클릭 시 갯수 바로 반영 되도록 수정
  app/(user)/cart/page.tsx
  app/(user)/my/address/page.tsx
  app/api/addresses/[id]/route.ts
  backend/address/applications/usecases/DeleteAddressUseCase.ts
  backend/address/domains/repositories/AddressRepository.ts
  backend/address/repositories/PrAddressRepository.ts
  components/cart/CartProduct/index.tsx
  components/common/Button/button.module.scss
  components/my/address/AddressModal/addressModal.module.scss
  components/my/address/AddressModal/index.tsx
  components/products/BottomFixButton/index.tsx
  components/products/BrandInfo/index.tsx
  components/saved/ProductSave/index.tsx
  store/likeStore.ts
Labels: hotfix

#75 [feat] 메인페이지 메인베너, 중간베너, 최근 본 상품 추가
  app/(user)/mainPage.module.scss
  app/(user)/page.tsx
  components/main/BannerSlide/bannerSlide.module.scss
  components/main/BannerSlide/index.tsx
  components/main/MiddleBanner/index.tsx
  components/main/MiddleBanner/middleBanner.module.scss
  components/main/RecentProducts/index.tsx
  components/main/RecentProducts/recentProducts.module.scss
  components/search/SearchCategory/index.tsx
  public/images/main_banner01.jpg
  public/images/main_banner02.jpg
  public/images/main_banner03.jpg
  public/images/main_banner04.png
  public/images/main_banner05.jpg
  public/images/middle_banner01.jpg
  public/images/middle_banner02.jpg
  public/images/middle_banner03.jpg
Labels: feat

#82 [hotfix] 주소록 메인 주소 안나오던것 수정, 중복 장바구니 상품 검증 추가
  app/(user)/LayoutWrapper.tsx
  app/(user)/my/address/page.tsx
  components/common/Header/index.tsx
  components/main/BannerSlide/index.tsx
  components/main/MiddleBanner/index.tsx
  components/main/MiddleBanner/middleBanner.module.scss
  components/products/BottomFixButton/index.tsx
  next.config.ts
  store/cartStore.ts
  utils/address/index.ts
Labels: hotfix

#79 [feat] 카테고리&브랜드 모달 구현
  app/api/brands/route.ts
  components/common/CategoryBrandModal/BrandMy.tsx
  components/common/CategoryBrandModal/BrandTab.tsx
  components/common/CategoryBrandModal/CategoryTab.tsx
  components/common/CategoryBrandModal/categoryBrandModal.module.scss
  components/common/CategoryBrandModal/index.tsx
  components/common/Header/header.module.scss
  components/common/Header/index.tsx
  components/common/SearchModal/index.tsx
  components/saved/EmptyText/index.tsx
  components/search/SearchBottomSheet/index.tsx
  components/search/SearchSort/index.tsx
  package.json
  public/icons/arrow_left.svg
  public/icons/hamburger.svg
  public/images/kakao.jpg
  services/brand/index.ts
Labels: feat

#89 [hotfix] 상품 상세페이지 로그인 체크 추가
  app/api/cart/route.ts
  components/main/RecentProducts/index.tsx
  components/products/BottomFixButton/index.tsx
  components/saved/ProductSave/index.tsx
Labels: hotfix

#91 [feat] AI 를 통한 이미지 검색 기능 추가
  app/(user)/ai-search/aiSearch.module.scss
  app/(user)/ai-search/page.tsx
  app/api/products/thumbnail/route.ts
  backend/products/applications/usecases/GetProductsThumbnail.ts
  backend/products/domains/repositories/ProductRepository.ts
  backend/products/repositories/PrProductsRepository.ts
  components/saved/ProductSave/index.tsx
  components/saved/ProductSave/productSave.module.scss
  package.json
  services/products/index.ts
Labels: feat, hotfix

#94 [hotfix, bug] 안드로이드 화면 밀림현상 css 수정, 회원가입에 헤더 추가, 리뷰 toast팝업 제거
  app/(user)/LayoutWrapper.tsx
  app/(user)/layout.tsx
  app/(user)/my/review/[orderId]/page.tsx
  components/auth/SignupForm/signupForm.module.scss
  styles/global.scss
Labels: bug, hotfix

#93 [Fix] qa 수정사항 반영, 파비콘, 로고이미지 추가
  app/favicon.ico
  components/common/BasicInput/basicInput.module.scss
  components/common/BasicInput/index.tsx
  components/common/BottomSheet/bottom_sheet.module.scss
  components/common/BottomSheet/index.tsx
  components/common/CategoryBrandModal/BrandTab.tsx
  components/common/CategoryBrandModal/categoryBrandModal.module.scss
  components/common/DragScroll/dragScroll.module.scss
  components/common/DragScroll/index.tsx
  components/common/Footer/index.tsx
  components/common/Header/index.tsx
  components/common/TabMenu/index.tsx
  components/common/TabMenu/tabMenu.module.scss
  components/search/SearchBottomSheet/index.tsx
  components/search/SearchBottomSheet/searchBottomSheet.module.scss
  components/search/SearchFilter/index.tsx
  package.json
  public/images/logo_white.png
Labels: refactor, hotfix

#97 [refactor] 상품상세 메타태그, 페이지 로딩, 없는 상품 접근시 페이지 추가
  app/(user)/LayoutWrapper.tsx
  app/(user)/layout.tsx
  app/(user)/mainPage.module.scss
  app/(user)/not-found.tsx
  app/(user)/payments/success/SuccessPage.module.scss
  app/(user)/payments/success/page.tsx
  app/(user)/products/[id]/page.tsx
  components/my/BuyList/buyList.module.scss
Labels: refactor

#99 [feat] 상품 상세 페이지 추천 상품 구간 추가
  app/(user)/products/[id]/page.tsx
  app/(user)/products/[id]/productDetail.module.scss
  app/api/products/recommend/route.ts
  backend/products/applications/usecases/GetRecomendProducts.ts
  backend/products/domains/entities/Products.ts
  backend/products/domains/repositories/ProductRepository.ts
  backend/products/repositories/PrProductsRepository.ts
  components/products/DetailLayout/detailLayout.module.scss
  components/products/DetailLayout/index.tsx
  components/products/ProductDetailImage/index.tsx
  components/products/Recommends/index.tsx
  components/products/Recommends/recommends.module.scss
  components/products/Tab/index.tsx
  components/products/Tab/tab.module.scss
  components/products/TextReview/index.tsx
  services/products/index.ts
  store/scrollStore.ts
  types/product.ts
Labels: feat, hotfix

#100 [feat] : 이벤트 페이지 추가, 헤더 경우에 따라노출되는 부분 객 1개로 통합관리
  app/(user)/LayoutWrapper.tsx
  app/(user)/event/event.module.scss
  app/(user)/event/fishhook/fishhook.module.scss
  app/(user)/event/fishhook/page.tsx
  app/(user)/event/page.tsx
  components/common/Header/header.module.scss
  components/common/Header/index.tsx
  constraint/header.ts
  middleware.ts
  public/images/event/bg.png
  public/images/event/bg2.png
  public/images/event/box2.png
  public/images/event/c_txt.png
  public/images/event/coin1.png
  public/images/event/coin2.png
  public/images/event/coin3.png
  public/images/event/coin4.png
  public/images/event/cont_3.png
  public/images/event/crucian_carp.png
  public/images/event/event_banner.png
  public/images/event/fishing_hook.png
  public/images/event/fishing_line.png
  public/images/event/flying_fish1.png
  public/images/event/flying_fish2.png
  public/images/event/hippocampus.png
  public/images/event/redfish1.png
  public/images/event/redfish2.png
  public/images/event/stripe_fish.png
  services/points/index.ts
  types/header.ts
Labels: feat, refactor

#103 [hotfix] 상품 상세페이지 헤더 변경으로 인한 높이수정, 탭부분 z-index 조정
  components/products/DetailLayout/detailLayout.module.scss
  components/products/Tab/tab.module.scss
Labels: hotfix

#105 [hotfix] 상세페이지 구매 버튼 z-index 조정, 리뷰 바텀시트 크기 조정
  components/products/BottomFixButton/bottomFixButton.module.scss
  components/products/ReviewBottomSheet/reviewBottomSheet.module.scss
Labels: hotfix

#107 [feat] Read.me 기본 골자 작성
  README copy.md
  README.md
Labels: feat
